/**:
  ros__parameters:
    command_topic: "/vehicle/vehicle_command"
    state_topic: "/vehicle/vehicle_kinematic_state"
    trajectory_topic: "/planning/trajectory"
    tf_topic: "/tf"
    static_tf_topic: "/tf_static"
    diagnostic_topic: "control_diagnostic"
    debug_trajectory_publish_period_ms: 100  # if 0 or missing, no publishing happens
    controller:
      interpolation: true
      sample_tolerance_ms: 20
      control_lookahead_ms: 500
      limits:
        min_longitudinal_velocity_mps: -1.7
        max_longitudinal_velocity_mps: 1.7
        min_lateral_velocity_mps: -3.0
        max_lateral_velocity_mps: 3.0
        min_acceleration_mps2: -3.0
        max_acceleration_mps2: 1.5
        min_yaw_rate_rps: -3.0
        max_yaw_rate_rps: 3.0
        min_jerk_mps3: -10.0
        max_jerk_mps3: 10.0
        min_steer_angle_rad: -0.6
        max_steer_angle_rad: 0.6
        min_steer_angle_rate_rps: -0.6
        max_steer_angle_rate_rps: 0.6
      vehicle:
        cg_to_front_m: 1.228
        cg_to_rear_m: 1.5618
        front_corner_stiffness: 17000.0
        rear_corner_stiffness: 20000.0
        mass_kg: 1460.0
        yaw_inertia_kgm2: 2170.0
        width_m: 2.0
        front_overhang_m: 1.05
        rear_overhang_m: 0.92
      behavior:
        stop_rate_mps2: 3.0
        time_step_ms: 100
        is_temporal_reference: true
      weights:
        nominal:                        # -- at each trajectory points --
          pose: 100.0                   # to make the pose same as the reference trajectory at each trajectory points
          heading: 50.0                 # to make the pose heading as the reference trajectory at each trajectory points
          longitudinal_velocity: 25.0   # to make the pose velocity as the reference trajectory at each trajectory points
          lateral_velocity: 0.0         # NOT USED
          yaw_rate: 0.0                 # NOT USED
          acceleration: 10.0            # to make the accelration zero
          jerk: 0.0                     # NOT USED
          steer_angle: 0.0              # to make the steering angle zero
          steer_angle_rate: 0.0         # NOT USED
        terminal:                       # -- at a trajectory tarminal point --
          pose: 10000.0                 # to make the pose same as the reference
          heading: 10000.0              # to make the heading same as the reference
          longitudinal_velocity: 100.0  # to make the velocity same as the reference
          lateral_velocity: 0.0         # NOT USED
          yaw_rate: 0.0                 # NOT USED
          acceleration: 0.0             # to make the accelration ZERO
          jerk: 0.0                     # NOT USED
          steer_angle: 0.0              # to make the steering angle ZERO
          steer_angle_rate: 0.0         # NOT USED
