# config/vlp16_test.param.yaml
/**:
  ros__parameters:
    ip: "192.168.1.102" #destination IP address
    port: 2369
    cloud_size:  55000
    topic: "points_raw"  # UdpDriverNode strictly expects to get the topic via `declare_parameter`.
    frame_id: "lidar_rear"
    timeout_ms: 10
    rpm:        600
