# # config/test.param.yaml
# ---
# lidar_front:
#   point_cloud_filter_transform_node:
#     ros__parameters:
#       timeout_ms:       110
#       pcl_size:         55000
#       input_frame_id:  "lidar_front"
#       output_frame_id: "base_link"
#       init_timeout_ms:  5000
#       expected_num_subscribers: 1
#       expected_num_publishers:  1
#       start_angle:            3.22886       # radius
#       end_angle:              3.05433
#       min_radius:             1.5           # meters
#       max_radius:             150.0
#       static_transformer:
#         quaternion:
#           x:                    0.0
#           y:                    0.0
#           z:                    0.0
#           w:                    1.0
#         translation:
#           x:                    0.0
#           y:                    0.0
#           z:                    0.0

# config/test.param.yaml
---
lidar_front:
  filter_transform_vlp16_front:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_front"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0  # radians 过滤垂直角度范围起始值
      end_angle:              6.28 # 过滤垂直角度范围终止值
      min_radius:             0.80  # meters 过滤最小距离   origin 3.0
      max_radius:             50.0 # 过滤最大距离           origin 150.0
      static_transformer: #从lidar_front转换到base_link
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.47         #1.498
          y:                    0.0          #-0.022
          z:                    0.86

lidar_rear:
  filter_transform_vlp16_rear:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_front"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            0.0       # radians
      end_angle:              6.28
      min_radius:             0.85       # meters
      max_radius:             50.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                    0.0
          w:                    1.0
        translation:
          x:                    0.47
          y:                    0.0
          z:                    0.86
